[package]
name = "flake"
version = "0.1.0"
authors = ["creepersaur"]
edition = "2024"

[dependencies]
anyhow = "1.0"
winit = { version = "0.30", features = ["android-native-activity"] }
env_logger = "0.10"
log = "0.4"
wgpu = "30.0"
pollster = "0.3"
bytemuck = { version = "1.24", features = [ "derive" ] }
cgmath = "0.18"
device_query = "2"
wgpu_text = "30.0.0"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]

[profile.dev.package."*"]
opt-level = 3
debug = "line-tables-only"

[profile.release]
opt-level = 3          # Maximum optimizations for speed (default is 3)
lto = true             # Enable Link Time Optimization across the entire crate
codegen-units = 1      # Reduce number of codegen units to 1 for better optimizations (disables parallel codegen for this profile)
panic = "abort"        # Remove unwinding logic to reduce binary size and improve performance
debug=false
strip = true           # Strip debug symbols and symbols/relocations from binary (optional, for smaller size)
